### ISSUE TITLE
Adapt to ROS Enhancement proposal 145

### ISSUE THREAD

**Issue by TobiSchluter** [larics/ros_lpms_imu#13]
After asking on ROS Answers I was pointed to ROS REP 145, which defines the standards for an IMU driver. Including which data to provide in which coordinate systems etc. See here: http://github.com/paulbovbel/rep/blob/master/rep-0145.rst

It is not yet official, discussion here (on hold until some "conversion tools" are ready): https://github.com/ros-infrastructure/rep/pull/95

It defines  which topics to use and a number of standard parameters that are not yet implemented by the LPMS driver.

**Comment by dmiklic** [comment]
Hi Tobi, thanks for digging up REP 145, it is exactly what we have been looking for :)

I have made PR #14 which adds some docs and addresses this issue partially. Please take a look and let me know what else should be done at this point. I'd say I need to remove the "-" signs when filling the orientation message.

**Comment by TobiSchluter** [comment]
Thank you for looking into this, what I've seen so far looks great. I'll have a closer look with the REP on my screen, time allowing either tomorrow afternoon (JST) or on Monday. I'm busy with a new version of LpSensor, I hope we can put that out soon to add a blocking interface & reduce CPU usage. After that, we will have a really nice package for ROS users :)

oh, and I didn't dig out that REP, it was dug out for me!

**Comment by TobiSchluter** [comment]
I don't have as much time as I wished for. I gave it a look-through, and I couldn't find anything that seemed off, but I don't have time to verify the conventions in detail.  That said, I'm very happy that you are doing this work!

**Comment by dmiklic** [comment]
Thanks! I'm also a bit pressed for time right now, but I'll get back to closing this issue as soon as my schedule clears up a bit.

**Comment by TobiSchluter** [comment]
No problem, please take your time, it's not like the ROS standard made any progress in the past few weeks, so we're still ahead :) We at LP are very happy that this is available, and I'm planning to spend a bit of time on it as soon as I can cut something out of my schedule.  After all, I promised you the blocking I/O in LpSensor (done, just needs to be pushed out). There are also lots of settings that could be handled by the driver, and I want to work on making at least the most basic ones available.

**Comment by TobiSchluter** [comment]
Long time no see. We have a new ROS driver for our sensors which should conform to enhancement proposal 145. It also uses our new OpenZen library to support all of our sensors, including the latest models. It is available from here. https://bitbucket.org/lpresearch/openzenros/src/master/

 We expect a blog post in the next few days. Anyway, I think I can close this issue :D

**Comment by dmiklic** [comment]
Thanks for the update @TobiSchluter. OpenZen looks great! I guess it makes this repo obsolete, so maybe I can put a note in the readme that this is obsolete and point people to the OpenZen driver. Or is there some legacy hardware that is not supported by OpenZen but can still use this driver?

**Comment by TobiSchluter** [comment]
Thank you. OpenZen is meant to supersede LpSensor completely, and it supports all our past sensors. So I think it is a really good idea if you could point to the new ROS driver.

We actually have a pull request for the ROS distro in the works, so we are hoping the new library will become "official" soon, see  https://github.com/ros/rosdistro/pull/24458

Thank you for your work! The discussions we had back then were actually very useful for this work, as we had already learnt about ROS conventions and the like :)
